version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.2
  ansible-playbook: orbss/ansible-playbook@0.0.5

jobs:
  execution-cloudformation:
     executor: aws-cli/default
     steps:
       - checkout
       - aws-cli/setup:
           aws_access_key_id: AWS_ACCESS_KEY_ID
           aws_secret_access_key: AWS_SECRET_ACCESS_KEY
           region: AWS_DEFAULT_REGION
       - run:
           name: deploy cloudformation
           command: |
             aws cloudformation deploy --template cloudformation/service.yml --stack-name webService
  execution-ansible:
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:C/2Tyc2h823YnNy9EMJfkoLmRI4b7hFIQKlf7mC2whU"
      - ansible-playbook/install:
          version: 11.1.0
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -i ansible/inventory

workflows:
  circleci-live-demo15-20241214-workflow:
    jobs:
      - execution-cloudformation
      - execution-ansible:
          requires:
            - execution-cloudformation
